- name: sources file
  template:
    src: sources.j2
    dest: /etc/apt/sources.list
  tags:
    - apt

- name: apt update
  apt:
    update_cache: yes
  tags:
    - apt

- name: auto clean
  apt:
    autoclean: yes
  tags:
    - apt

- name: auto remove
  apt:
    autoremove: yes
  tags:
    - apt
