# Standards: 0.1
---
- name: Write sources list
  register: apt_sources
  template:
    src: sources.j2
    dest: /etc/apt/sources.list
  tags:
    - apt

- name: Write periodic config
  template:
    src: periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
  tags:
    - apt

- name: Write unattended-upgrades config
  template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
  tags:
    - apt

- name: Update apt cache
  when: apt_force_update or apt_sources.changed
  apt:
    update_cache: yes
  tags:
    - apt

...
