# Standards: 1.2
---
- name: Write sources list
  notify:
    - Update apt
  template:
    src: sources.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - apt

- name: Update apt cache
  when: apt_force_update
  register: result
  until: not result.failed | bool
  retries: 6
  delay: 10
  apt:
    update_cache: True
  tags:
    - apt

- name: Install required packages
  loop:
    - unattended-upgrades
  package:
    name: "{{ item }}"
    state: present
  tags:
    - apt

- name: Write periodic config
  template:
    src: periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - apt

- name: Write unattended-upgrades config
  template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - apt

- name: Drop redundant configs
  loop: "{{ apt_redundant_configs }}"
  file:
    path: "/etc/apt/apt.conf.d/{{ item }}"
    state: absent
  tags:
    - apt

...
