---
- name: deploy apt sources file
  template:
    src: etc/apt/sources.list.j2
    dest: /etc/apt/sources.list
  register: apt_sources
  tags:
    - apt

- name: deploy apt periodic config
  template:
    src: etc/apt/apt.conf.d/10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
  tags:
    - apt

- name: deploy unattended-upgrade config
  template:
    src: etc/apt/apt.conf.d/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
  tags:
    - apt

- name: apt update
  when: apt_force_update or apt_sources.changed
  apt:
    update_cache: yes
  tags:
    - apt

...
